---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: release-<VERSION>-mac-x86-14-
  labels:
    app.kubernetes.io/product: crc
    app.kubernetes.io/ci: tekton
spec:
  pipelineRef:
    name: crc-qe-baremetal
  params:
  - name: host-config-secret
    value: host-mac-1-brno
  - name: downloadable-url
    value: https://download.hosts.prod.upshift.rdu2.redhat.com/etera/crc/2/<VERSION_1>/<VERSION>/staging
  - name: shasum-file
    value: sha256sum.txt
  # - name: run-integration
  #   value: 'false'
  - name: integration-timeout
    value: '120m'
  - name: s3-folder-path
    value: 'release/<VERSION>/ocp'
  - name: test-catelog
    value: "release-test"
  workspaces:
  - name: pipelines-data
    persistentVolumeClaim:
      claimName: pipelines-data
  - name: ocp-pullsecret
    secret:
      secretName: crc-crc-qe
  - name: reportportal-credentials
    secret:
      secretName: reportportal-crc
  timeout: "5h"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: release-<VERSION>-mac-x86-13-
  labels:
    app.kubernetes.io/product: crc
    app.kubernetes.io/ci: tekton
spec:
  pipelineRef:
    name: crc-qe-baremetal
  params:
  - name: host-config-secret
    value: host-mac-2-brno
  - name: downloadable-url
    value: https://download.hosts.prod.upshift.rdu2.redhat.com/etera/crc/2/<VERSION_1>/<VERSION>/staging
  - name: shasum-file
    value: sha256sum.txt
  # - name: run-integration
  #   value: 'false'
  - name: integration-timeout
    value: '120m'
  - name: s3-folder-path
    value: 'release/<VERSION>/ocp'
  - name: test-catelog
    value: "release-test"
  workspaces:
  - name: pipelines-data
    persistentVolumeClaim:
      claimName: pipelines-data
  - name: ocp-pullsecret
    secret:
      secretName: crc-crc-qe
  - name: reportportal-credentials
    secret:
      secretName: reportportal-crc
  timeout: "5h"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: release-<VERSION>-mac-arm64-13-
  labels:
    app.kubernetes.io/product: crc
    app.kubernetes.io/ci: tekton
spec:
  pipelineRef:
    name: crc-qe-baremetal
  params:
  - name: host-config-secret
    value: host-mac-4-brno
  - name: downloadable-url
    value: https://download.hosts.prod.upshift.rdu2.redhat.com/etera/crc/2/<VERSION_1>/<VERSION>/staging
  - name: shasum-file
    value: sha256sum.txt
  - name: s3-folder-path
    value: 'release/<VERSION>/ocp'
  # - name: run-integration
  #   value: 'false'
  - name: integration-timeout
    value: '120m'
  - name: test-catelog
    value: "release-test"
  workspaces:
  - name: pipelines-data
    persistentVolumeClaim:
      claimName: pipelines-data
  - name: ocp-pullsecret
    secret:
      secretName: crc-crc-qe
  - name: reportportal-credentials
    secret:
      secretName: reportportal-crc
  timeout: "5h"