# # RHEL 8.9
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: release-<VERSION>-rhel89-
  labels:
    redhat.com/product: openshift-local
    dev.lifecycle.io/phase: qe
spec:
  pipelineRef:
    name: crc-qe-baremetal
  params:
  - name: host-config-secret
    value: host-rhel-1-brno
  - name: downloadable-url
    value: https://download.hosts.prod.upshift.rdu2.redhat.com/etera/crc/2/<VERSION_1>/<VERSION>/staging
  - name: shasum-file
    value: sha256sum.txt
  - name: s3-folder-path
    value: 'release/<VERSION>/ocp'
  - name: test-catelog
    value: "release-test"
  workspaces:
  - name: pipelines-data
    persistentVolumeClaim:
      claimName: pipelines-data
  - name: ocp-pullsecret
    secret:
      secretName: crc-crc-qe
  - name: reportportal-credentials
    secret:
      secretName: reportportal-crc
  timeout: "7h"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: release-<VERSION>-rhel93-
spec:
  pipelineRef:
    name: crc-qe-virtualized
  params:
  - name: rhel-version
    value: '9.4'
  - name: internal-base-url
    value: https://download.hosts.prod.upshift.rdu2.redhat.com/etera/crc/2/<VERSION_1>/<VERSION>/staging
  - name: internal-asset-name
    value: crc-linux-amd64.tar.xz
  - name: internal-shasum-name
    value: sha256sum.txt
  - name: shasum-file
    value: sha256sum.txt
  - name: s3-folder-path
    value: 'release/<VERSION>/ocp'
  workspaces:
  - name: pipelines-data
    persistentVolumeClaim:
      claimName: pipelines-data
  - name: cloud-credentials
    secret:
      secretName: aws-crcqe-bot
  - name: rh-account-secret
    secret:
      secretName: credentials-rh-subs-crcqe-prod
  - name: ocp-pullsecret
    secret:
      secretName: crc-crc-qe
  - name: reportportal-credentials
    secret:
      secretName: reportportal-crc
  timeout: "5h"
