---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: release-<VERSION>-windows-11-
  labels:
    redhat.com/product: openshift-local
    dev.lifecycle.io/phase: qe
spec:
  pipelineRef:
    name: crc-qe-baremetal
  params:
  - name: host-config-secret
    value: host-windows-1-brno
  - name: downloadable-url
    value: https://download.hosts.prod.upshift.rdu2.redhat.com/etera/crc/2/<VERSION_1>/<VERSION>/staging
  - name: shasum-file
    value: sha256sum.txt    
  - name: s3-folder-path
    value: 'release/<VERSION>/ocp'
  - name: test-catelog
    value: "release-test"
  workspaces:
  - name: pipelines-data
    persistentVolumeClaim:
      claimName: pipelines-data
  - name: ocp-pullsecret
    secret:
      secretName: crc-crc-qe
  - name: reportportal-credentials
    secret:
      secretName: reportportal-crc
  timeout: "5h"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: release-<VERSION>-windows10-22h2-ent-
spec:
  pipelineRef:
    name: crc-qe-virtualized
  params:
  - name: windows-version
    value: '10' 
  - name: windows-featurepack
    value: 22h2-ent
  - name: internal-base-url
    value: https://download.hosts.prod.upshift.rdu2.redhat.com/etera/crc/2/<VERSION_1>/<VERSION>/staging
  - name: internal-asset-name
    value: crc-windows-installer.zip
  - name: internal-shasum-name
    value: sha256sum.txt
  - name: shasum-file
    value: sha256sum.txt
  - name: s3-folder-path
    value: 'release/<VERSION>/ocp'
  workspaces:
  - name: pipelines-data
    persistentVolumeClaim:
      claimName: pipelines-data
  - name: cloud-credentials
    secret:
      secretName: az-crcqe-bot
  - name: ocp-pullsecret
    secret:
      secretName: crc-crc-qe
  - name: reportportal-credentials
    secret:
      secretName: reportportal-crc
  timeout: "5h"

  

            