apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: crc-bundle-test-microshift-<BUNDLE_VERSION>-mac-arm64-
spec:
  pipelineRef:
    name: crc-qe-latest
  params:
  - name: preset 
    value: microshift
  - name: bundle-name
    value: "crc_microshift_vfkit_<BUNDLE_VERSION>_arm64.crcbundle"
  - name: bundle-shasumfile
    value: sha256sum.txt
  - name: bundle-base-url
    value: "https://cdk-builds.usersys.redhat.com/builds/crc/bundles/microshift/<BUNDLE_VERSION>"
  - name: e2e-tag
    value: "@story_microshift"
  - name: integration-tag
    value: "microshift-preset"
  - name: s3-path
    value: nightly/microshift/<BUNDLE_VERSION>/darwin-arm64
  - name: test-catalog
    value: bundle-test
  workspaces:
    - name: storage 
      persistentVolumeClaim:
        claimName: pipelines-data
    - name: builder-host-info
      secret:
        secretName: host-mac-1-brno
    - name: aws-credentials
      secret:
        secretName: aws-crcqe-bot
    - name: s3-credentials
      secret:
        secretName: s3-aws-crcqe-asia
    - name: tester-host-info
      secret:
        secretName: host-mac-4-brno
    - name: ocp-pullsecret
      secret:
        secretName: crc-crc-qe
    - name: reportportal-credentials
      secret:
        secretName: reportportal-crc
  timeout: "5h"