apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: crc-bundle-test-microshift-<BUNDLE_VERSION>-rhel-
spec:
  pipelineRef:
    name: crc-qe-latest
  params:
  - name: host-config-secret
    value: "host-rhel-1-brno"
  - name: builder-config-secret
    value: ""
  - name: preset 
    value: microshift
  - name: bundle-version
    value: "<BUNDLE_VERSION>"
  - name: bundle-shasumfile
    value: sha256sum.txt
  - name: bundle-url
    value: "https://cdk-builds.usersys.redhat.com/builds/crc/bundles/microshift/<BUNDLE_VERSION>"
  - name: e2e-tag
    value: "@story_microshift"
  - name: integration-tag
    value: "microshift-preset"
  - name: s3-folder-path
    value: nightly/microshift/<BUNDLE_VERSION>
  - name: test-catelog
    value: bundle-test
  workspaces:
  - name: pipelines-data
    persistentVolumeClaim:
      claimName: pipelines-data
  - name: ocp-pullsecret
    secret:
      secretName: crc-crc-qe
  - name: reportportal-credentials
    secret:
      secretName: reportportal-crc
  timeout: "5h"