---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: crc-interop-ocp-<VERSION>-mac-
spec:
  pipelineRef:
    name: crc-qe-latest
  params:
  - name: bundle-name
    value: crc_vfkit_<VERSION>_amd64.crcbundle
  - name: bundle-shasumfile
    value: bundles.sha256
  - name: bundle-base-url
    value: "https://crcqe-asia.s3.ap-south-1.amazonaws.com/nightly/ocp/<VERSION>"
  - name: s3-path
    value: nightly/ocp/<VERSION>
  - name: e2e-tag
    value: "~@minimal && ~@story_microshift"
  - name: integration-tag
    value: "! microshift-preset"
  - name: test-catalog
    value: ocp-interop-test
  workspaces:
    - name: storage 
      persistentVolumeClaim:
        claimName: pipelines-data
    - name: builder-host-info
      secret:
        secretName: host-mac-1-brno
    - name: aws-credentials
      secret:
        secretName: aws-crcqe-bot
    - name: s3-credentials
      secret:
        secretName: s3-aws-crcqe-asia
    - name: tester-host-info
      secret:
        secretName: host-mac-2-brno
    - name: ocp-pullsecret
      secret:
        secretName: crc-crc-qe
    - name: reportportal-credentials
      secret:
        secretName: reportportal-crc
  timeout: "5h"
